Repository googleapis/python-assured-workloads, pull requests merged in 2021-04, with the labels that each got.

#23 chore: re-add tests/unit to coverage
  noxfile.py
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: none

#24 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: full

#25 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: full, samples

#27 chore: prevent normalization of semver versioning
  setup.py
Labels: api: assuredworkloads, automerge, cla: yes

#26 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: assuredworkloads, automerge, cla: yes, context: full

#28 chore(revert): revert preventing normalization
  setup.py
Labels: api: assuredworkloads, cla: yes
